### ISSUE TITLE
Url change when page or tag change

### ISSUE THREAD

**Issue by tranlehaiquan** [arrlancore/nextjs-ssr-real-world-app-example#11]
When page change or tag change, url will change.
#10 Pull Request here

**Comment by tranlehaiquan** [comment]
T_T fix eslint. I don't ever touch to another file and it said ``Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style```

**Comment by arrlancore** [comment]
Thank you @tranlehaiquan , are you using window?
Regarding your PR I have some comments, please check

**Comment by tranlehaiquan** [comment]
@arrlancore I have fixed : D
